TienDat_DotNetCore/Models/Domain/Employee.cs
namespace TienDat_DotNetCore.Models.Domain
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public long Salary { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Department { get; set; }
    }
}

TienDat_DotNetCore/Pages/Employees/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TienDat_DotNetCore.Data;
using TienDat_DotNetCore.Models.ViewModels;
using TienDat_DotNetCore.Models.Domain;
using Microsoft.AspNetCore.Authorization;

namespace TienDat_DotNetCore.Pages.Employees
{
    [Authorize(Policy = "AdminOnly")]
    public class AddModel : PageModel
    {
        private readonly RazorPagesDB dBcontext;

        public AddModel(RazorPagesDB DBcontext)
        {
            this.dBcontext = DBcontext;
        }
        [BindProperty]
        public AddEmployeeViewModel AddEmployeeRequest { get; set; }
        public void OnGet()
        {
        }
        public void OnPost()
        {
            //chuyển viewmodel sang domainmodel
            var employeeDomainModel = new Employee
            {
                Name = AddEmployeeRequest.Name,
                Email = AddEmployeeRequest.Email,
                Salary = AddEmployeeRequest.Salary,
                DateOfBirth = AddEmployeeRequest.DateOfBirth,
                Department = AddEmployeeRequest.Department,
            };
            dBcontext.Employees.Add(employeeDomainModel);
            dBcontext.SaveChanges();
            ViewData["Message"] = "Thêm nhân viên thành công!";
        }
    }
}

TienDat_DotNetCore/Pages/Employees/Edit.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TienDat_DotNetCore.Data;
using TienDat_DotNetCore.Models.ViewModels;

namespace TienDat_DotNetCore.Pages.Employees
{
    [Authorize(Policy = "AdminOnly")]
    public class EditModel : PageModel
    {
        private readonly RazorPagesDB dBcontext;
        [BindProperty]
        public EditEmployeeViewModel EditEmployeeViewModel { get; set; }
        public EditModel(RazorPagesDB DBcontext)
        {
            this.dBcontext = DBcontext;
        }
        public void OnGet(Guid id)
        {
            var employee = dBcontext.Employees.Find(id);
            if (employee != null)
            {
                //chuyển domain model sang view model
                EditEmployeeViewModel = new EditEmployeeViewModel()
                {
                    Id = employee.Id,
                    Name = employee.Name,
                    Salary = employee.Salary,
                    DateOfBirth = employee.DateOfBirth,
                    Email = employee.Email,
                    Department = employee.Department,
                };
            }
        }
        public void OnPostUpdate()
        {
            if (EditEmployeeViewModel != null)
            {
                var existingEmployee = dBcontext.Employees.Find(EditEmployeeViewModel.Id);
                if (existingEmployee != null)
                {
                    // chuyển view model sang domain model
                    existingEmployee.Id = EditEmployeeViewModel.Id;
                    existingEmployee.Name = EditEmployeeViewModel.Name;
                    existingEmployee.Salary = EditEmployeeViewModel.Salary;
                    existingEmployee.Email = EditEmployeeViewModel.Email;
                    existingEmployee.Department = EditEmployeeViewModel.Department;
                    dBcontext.SaveChanges();
                    ViewData["Message"] = "Sửa thông tin thành công!";
                }
            }

        }
        public IActionResult OnPostDelete()
        {
            var existingEmployee = dBcontext.Employees.Find(EditEmployeeViewModel.Id);
            if (existingEmployee != null)
            {
                dBcontext.Employees.Remove(existingEmployee);
                dBcontext.SaveChanges();
                return RedirectToPage("/Employees/List");
            }
            return Page();
        }
    }
}

TienDat_DotNetCore/Pages/Employees/List.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TienDat_DotNetCore.Data;

namespace TienDat_DotNetCore.Pages.Employees
{
    [Authorize(Policy = "AdminOnly")]
    public class ListModel : PageModel
    {
        private readonly RazorPagesDB dBcontext;
        public List<Models.Domain.Employee> Employees { get; set; }
        public ListModel(RazorPagesDB DBcontext)
        {
            this.dBcontext = DBcontext;
        }
        public void OnGet()
        {
            Employees = dBcontext.Employees.ToList();
        }
    }
}

TienDat_DotNetCore/Pages/Employees/Add.cshtml
@page
@model TienDat_DotNetCore.Pages.Employees.AddModel
@{
    var message = ViewData["Message"]?.ToString();
}
<form method="post">
    <h1 class="mb-3">Add Nhân Viên</h1>
    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }
    <div class="mb-3">
        <label class="form-label">Tên Nhân Viên</label>
        <input type="text" class="form-control" asp-for="AddEmployeeRequest.Name" />
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" asp-for="AddEmployeeRequest.Email" />
    </div>
    <div class="mb-3">
        <label class="form-label">Lương</label>
        <input type="number" class="form-control" asp-for="AddEmployeeRequest.Salary" />
    </div>
    <div class="mb-3">
        <label class="form-label">Ngày Sinh</label>
        <input type="date" class="form-control" asp-for="AddEmployeeRequest.DateOfBirth" />
    </div>
    <div class="mb-3">
        <label class="form-label">Khoa</label>
        <input type="text" class="form-control" asp-for="AddEmployeeRequest.Department" />
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Lưu</button>
    </div>

</form>

TienDat_DotNetCore/Pages/Employees/Edit.cshtml
@page "{id:Guid}"
@model TienDat_DotNetCore.Pages.Employees.EditModel
@{
    var message = ViewData["Message"]?.ToString();
}
<form method="post">
    <h1 class="mb-3">Sửa thông tin</h1>
    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }
    <div class="mb-3">
        <label class="form-label">Id</label>
        <input type="text" class="form-control" asp-for="EditEmployeeViewModel.Id" readonly />
    </div>
    <div class="mb-3">
        <label class="form-label">Tên nhân viên</label>
        <input type="text" class="form-control" asp-for="EditEmployeeViewModel.Name" />
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" asp-for="EditEmployeeViewModel.Email" />
    </div>
    <div class="mb-3">
        <label class="form-label">Lương</label>
        <input type="number" class="form-control" asp-for="EditEmployeeViewModel.Salary" />
    </div>
    <div class="mb-3">
        <label class="form-label">Ngày sinh</label>
        <input type="datetime" class="form-control" asp-for="EditEmployeeViewModel.DateOfBirth" />
    </div>
    <div class="mb-3">
        <label class="form-label">Khoa</label>
        <input type="text" class="form-control" asp-for="EditEmployeeViewModel.Department" />
    </div>
    <div class="mb-3 d-flex justify-content-between" >
        <button type="submit" class="btn btn-primary" asp-page-handler="Update">Cập nhật</button>
        <button type="submit" class="btn btn-danger" asp-page-handler="Delete">Xóa</button>
    </div>
</form>

TienDat_DotNetCore/Pages/Employees/List.cshtml
@page
@model TienDat_DotNetCore.Pages.Employees.ListModel
@{
}

<h1 class="mb-3">Danh sách nhân viên</h1>
@if (Model.Employees != null && Model.Employees.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Tên nhân viên</th>
                <th>Email</th>
                <th>Lương</th>
                <th>Khoa</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model.Employees)
            {
                <tr>
                    <td>@employee.Id</td>
                    <td>@employee.Name</td>
                    <td>@employee.Email</td>
                    <td>@employee.Salary</td>
                    <td>@employee.Department</td>
                    <td>
                        <a href="/Employees/Edit/@employee.Id" class="btn btn-dark">Sửa thông tin</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Không có nhân viên</p>
}